# Tournament xG Analysis - WWC 2023

This notebook is lesson 6 of the Soccermatics course by David Sumpter.

**Goals:**
- Load all 64 matches from the Women's World Cup 2023
- Calculate xG for every team across the tournament
- Build a tournament table ranked by xG performance
- Compare xG ranking vs actual points ranking

**Libraries used:** `statsbombpy`, `pandas`, `matplotlib`

In [2]:
#Loading Imports
from statsbombpy import sb
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Laod all 64 matches from the Women's World Cup 2023
matches = sb.matches(competition_id=72, season_id=107)
print(f"Total matches: {len(matches)}")
matches[['match_id', 'home_team', 'away_team', 'home_score', 'away_score']].head()

c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Total matches: 64

   match_id          home_team          away_team  home_score  away_score
0   3904629  Australia Women's    England Women's           1           3
1   3906390      Spain Women's    England Women's           1           0
2   3906389     Sweden Women's  Australia Women's           2           0
3   3904628      Spain Women's     Sweden Women's           2           1
4   3893806      Spain Women's     Zambia Women's           5           0

In [ ]:
#Loop that goes through each match and calculates the xG for each team
match_ids = matches['match_id'].tolist()

all_xg = []

for match_id in match_ids:
    events = sb.events(match_id=match_id)
    shots = events[events['type'] == 'Shot']
    
    for team, group in shots.groupby('team'):
        all_xg.append({
            'match_id': match_id,
            'team': team,
            'xg': group['shot_statsbomb_xg'].sum()
        })

xg_df = pd.DataFrame(all_xg)
xg_df.head(10)

c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\osisi\OneDrive\Desktop\dataComics\soccermatics-course01\venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

   match_id               team        xg
0   3904629  Australia Women's  1.142442
1   3904629    England Women's  1.052779
2   3906390    England Women's  0.469679
3   3906390      Spain Women's  2.194123
4   3906389  Australia Women's  0.743337
5   3906389     Sweden Women's  1.570150
6   3904628      Spain Women's  1.375955
7   3904628     Sweden Women's  0.790859
8   3893806      Spain Women's  3.775187
9   3893806     Zambia Women's  0.406064

In [5]:
#Group by team and sum the xG for each team
tournament_xg = xg_df.groupby('team')['xg'].sum().reset_index()
tournament_xg.columns = ['team', 'total_xg']
tournament_xg = tournament_xg.sort_values('total_xg', ascending=False).reset_index(drop=True)
tournament_xg['total_xg'] = tournament_xg['total_xg'].round(2)
tournament_xg.head(10)

                    team  total_xg
0      Australia Women's     19.38
1          Spain Women's     17.80
2         France Women's     17.49
3         Sweden Women's     17.27
4  United States Women's     13.68
5        England Women's     13.52
6          Japan Women's     10.69
7    Netherlands Women's      8.28
8        Nigeria Women's      7.01
9         Norway Women's      6.30

In [ ]:
#Add a rank column to the tournament_xg dataframe
tournament_xg['xg_rank'] = tournament_xg.index + 1
print(tournament_xg[['team', 'total_xg', 'xg_rank']].to_string())

                           team  total_xg  xg_rank
0             Australia Women's     19.38        1
1                 Spain Women's     17.80        2
2                France Women's     17.49        3
3                Sweden Women's     17.27        4
4         United States Women's     13.68        5
5               England Women's     13.52        6
6                 Japan Women's     10.69        7
7           Netherlands Women's      8.28        8
8               Nigeria Women's      7.01        9
9                Norway Women's      6.30       10
10               Brazil Women's      5.80       11
11              Germany Women's      5.13       12
12         South Africa Women's      4.95       13
13          Switzerland Women's      4.63       14
14                Italy Women's      4.42       15
15             Portugal Women's      4.23       16
16             Colombia Women's      4.14       17
17               Canada Women's      3.91       18
18              Denmark Women's      3.82       19
19          New Zealand Women's      3.69       20
20              Morocco Women's      3.03       21
21       Korea Republic Women's      2.73       22
22           Costa Rica Women's      2.57       23
23             China PR Women's      2.54       24
24               Zambia Women's      2.35       25
25  Republic of Ireland Women's      2.21       26
26               Panama Women's      2.10       27
27              Jamaica Women's      2.09       28
28                Haiti Women's      1.93       29
29            Argentina Women's      1.16       30
30          Philippines Women's      0.59       31
31              Vietnam Women's      0.44       32